/* Precompiled Headers */
#include "attr.hpp"
#include "algo_par.hpp"
#include "bimap.hpp"
#include "fs.hpp"
#include "graph.hpp"
#include "macros.hpp"
#include "non-copyable.hpp"
#include "opt-util.hpp"
#include "preprocessor.hpp"
#include "project.hpp"
#include "pugiconfig.hpp"
#include "pugixml.hpp"
#include "solution.hpp"
#include "stopwatch.hpp"
#include "string-util.hpp"
#include "types.hpp"
#include "util.hpp"
#include "xml-utils.hpp"
#include <algorithm>
#include <assert.h>
#include <cctype>
#include <chrono>
#include <exception>
#include <experimental/filesystem>
#include <float.h>
#include <fstream>
#include <functional>
#include <iomanip>
#include <iosfwd>
#include <iostream>
#include <istream>
#include <iterator>
#include <limits.h>
#include <map>
#include <math.h>
#include <new>
#include <optional>
#include <ostream>
#include <regex>
#include <setjmp.h>
#include <sstream>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <string>
#include <string_view>
#include <thread>
#include <tuple>
#include <type_traits>
#include <unordered_map>
#include <vector>
#include <wchar.h>
