// Generated by nr-make

#include "pugixml.hpp"

#include <string>
#include <iostream>
#include <stdexcept>

using namespace std;
using namespace pugi;

void parse( xml_document& doc, string file ) {

    xml_parse_result res = doc.load_file( file.c_str() );

    if( res )
        return;

    cerr << "XML ["
         << file
         << "] parsed with errors, attr value: ["
         << doc.child("node").attribute("attr").value()
         << "]\n"
         << "Error description: " << res.description()
         << "\n"
         << "Error offset: " << res.offset << " "
         << "(error at [" << res.offset << "]"
         << "\n\n";
    throw runtime_error( "error" );
}

int main()
{
    xml_document doc;

    parse( doc, "../samples/simple.xml" );

    cout << "Load successful: "
         << doc.child("root_node")
            .child("child")
            .attribute("color")
            .value()
         << endl;
    return 0;
}
